### ISSUE TITLE
Falta la descripción del Bubble sort

### ISSUE THREAD

**Issue by ericbrandwein** [CubaWiki/AED2-ApunteFinal-Rama#11]
No se si a alguien le sirve, pero tener una subsection vacía con ese título sirve poco: https://github.com/CubaWiki/AED2-ApunteFinal-Rama/blob/a5b40d3e438fff0da7b95ecc15d4fcab51886000/algoritmos.tex#L236

**Comment by ramaroberto** [comment]
Es un placeholder, te animas a agregarla? Creo que se puede poner al principio de la seccion con una descripcion resumida del algoritmo, no es algo que realmente sirva ni dificil. Adicionalmente podes escribir el pseudocodigo.
