### ISSUE TITLE
Error en el gráfico de la rotación RR del AVL

### ISSUE THREAD

**Issue by FlyingPumba** [CubaWiki/AED2-ApunteFinal-Rama#4]
En la última figura (la tercera), el hijo derecho de P ahora tiene altura h+1, en vez de h. Se puede ver en [wikipedia para el caso LL](http://es.wikipedia.org/wiki/%C3%81rbol_AVL#Rotaciones), que la altura de los subárboles de P o Q no varia.
Lo corregiría yo pero no sé como editar/volver a generar esos PDFs.

**Comment by ramaroberto** [comment]
Hola!

Tenes razón. Si lo podes / queres corregir vos, los gráficos están hechos con yEd, lo podes bajar de acá:

http://www.yworks.com/en/products/yfiles/yed/

Fijate que para cada grafico estan los archivitos correspondientes "graphml" que podes abrir con yEd y editar, es muy fácil de usar. Te recomiendo que de hacer más gráficos lo utilices, y de paso te pido que si hiciste los que agregaste en photoshop / illustrator o corel subas los sources (si los tenes), por si alguien quiere editar algo no tiene que hacer todo de cero!

De ultima lo retoco yo mas tarde, ahora estoy ocupado con otras cosas.

Muchas gracias por todos tus aportes!

Saludos!

**Comment by FlyingPumba** [comment]
Genial, no me había dado cuenta que estaban los archivos .graphml en la carpeta gráficos. Yo lo arreglo y lo cambio.
Los que subí de skip-lists y tries los saqué de internet, así que no tengo los sources. Quizás más adelante (sí tengo tiempo) los puedo hacer de cero en yEd y ya nos queda el archivo .graphml.

Por nada ! Tengo varios cambios más que voy a ir subiendo después. :+1: 
Saludos.

**Comment by ramaroberto** [comment]
Arreglado en pull request #6.
